title: "Decnet AI Level Scatter"
description: "Professional AI-Powered Environment Generation & Placement Assistant for Unity."
remote_theme: just-the-docs/just-the-docs

url: "https://decnet-games.github.io"
baseurl: "/AI-Level-Scatter-Doc"

# Navigation settings
nav_sort: case_insensitive

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

aux_links:
  "Asset Store Page": "https://assetstore.unity.com"
  "GitHub Repository": "https://github.com/DecNet-Games/AI-Level-Scatter"
